/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import napakalaki.*;
/**
 *
 * @author pako
 */
public class NapakalakiView extends javax.swing.JFrame {

    Napakalaki napakalakiModel;
    /**
     * Creates new form NapakalakiView
     */
    public NapakalakiView() {
        initComponents();
    }

    public void setNapakalaki(Napakalaki nuevo) {
        napakalakiModel = nuevo;
        this.monsterView1.setMonster(nuevo.getCurrentMonster());
        this.playerView1.setPlayer(nuevo.getCurrentPlayer());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        monsterView1 = new GUI.MonsterView();
        ConocerMonstruo = new javax.swing.JButton();
        bCombatir = new javax.swing.JButton();
        SigTurno = new javax.swing.JButton();
        txtResultado = new javax.swing.JTextField();
        playerView1 = new GUI.PlayerView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("NapakalakiView"));

        ConocerMonstruo.setText("Meet the Monster");

        bCombatir.setText("Combat");
        bCombatir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCombatirActionPerformed(evt);
            }
        });

        SigTurno.setText("Next turn");
        SigTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SigTurnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(playerView1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monsterView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ConocerMonstruo)
                            .addComponent(bCombatir)
                            .addComponent(SigTurno))
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtResultado))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(ConocerMonstruo)
                        .addGap(19, 19, 19)
                        .addComponent(bCombatir)
                        .addGap(18, 18, 18)
                        .addComponent(SigTurno)
                        .addGap(18, 18, 18)
                        .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(playerView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monsterView1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SigTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SigTurnoActionPerformed
        /*if(napakalakiModel.getCurrentPlayer().validState() == true)
        {
            napakalakiModel.nextTurn();
            MonsterView.setVisible(false);
            SigTurno.setEnabled(false);
            PlayerView.setPlayer(napakalakiModel.getCurrentPlayer());
            playerView.setMakeTreasuresVisibleEnabled(true);
            playerView.setBuyLevelsEnabled(true);
            playerView.setDiscardTreasuresEnabled(true);
            resultadoText.setText(null);
            meetMonsterButton.setEnabled(true);
        }
        else
        resultadoText.setText("No puedes pasar al siguiente turno");*/
    }//GEN-LAST:event_SigTurnoActionPerformed

    private void bCombatirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCombatirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCombatirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConocerMonstruo;
    private javax.swing.JButton SigTurno;
    private javax.swing.JButton bCombatir;
    private javax.swing.JPanel jPanel1;
    private GUI.MonsterView monsterView1;
    private GUI.PlayerView playerView1;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
